[package]
name = "carbon-admin-ui"
version = "0.1.0"
authors = ["Chirdeep Tomar <chirdeep.tomar@gmail.com>"]
edition = "2021"

[[bin]]
name = "carbon-admin-ui"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.2", features = ["router"] }
wasm-bindgen = "0.2.105"
wasm-bindgen-cli = "0.2.105"
wasm-bindgen-futures = "0.4.50"
getrandom = { version = "0.3.4", features = ["wasm_js"] }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
