[package]
name = "storage-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
foyer.workspace = true
moka.workspace = true
tokio.workspace = true

carbon.workspace = true
shared.workspace = true
