[package]
name = "carbon"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.68"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
serde_json = "1.0"
sled = "0.34"
tokio = { version = "1.48.0", features = ["sync"] }
tempfile = "3.23.0"
tracing = "0.1"

shared = { path = "../shared" }
